### PR TITLE
TypeScript Port

### PR DESCRIPTION
**Pull request by codecop**
* TypeScript Port
* Make master branch similar to with_tests branch (mainly adding OldOrder to all sample objects).

### CODE REVIEW

**Comment by emilybache** [comment]
I'm not keen to have OldOrder included in the start position. I see it as part of understanding the exercise to realize you need this and have to add it.
I would like the TypeScript port though.

**Comment by codecop** [comment]
I see. I will remove it again.

**Comment by codecop** [comment]
OldOrder removed by changing last commit.

**Comment by emilybache** [comment]
Thankyou, that's just what I wanted

**Pull request merged**
